---
title: "数据库管理规则"
author: "胡华平"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("rvest")
require("stringr")
require("tidyverse")
require("tidyselect")
```


# 研究目标

我国粮食贸易中心，传统以来是在美洲，如果考虑到把这种贸易关系重心转移到“一带一路”国家，那么目前“一带一路”国家与我国农业贸易的情况如何？如果要承接这种重心转移，还需要哪些条件？以后该如何分步骤进行贸易重心转移（政策设计）？

# 数据目标

时间范围：2000年至今（因为2001年中国加入了WTO，这个可以是一个关键节点）

国家范围：关注几个重点国家和地区即可。因为数据上还不清楚，所以可以初步从文献和官方材料里（主要是农业部）来框定几个国家。初步：

    - 美洲：美国，加拿大，墨西哥、巴西、阿根廷
    - 一带一路国家：（中国）、俄罗斯、印度、（欧盟）。。。

农产品范围：主要还是关注主粮和重要饲用粮。先从下面几类产品入手。
    - 主粮包括：小麦、大米
    - 饲用粮包括：大豆、玉米
    - 畜禽产品：猪肉、牛肉、羊肉和鸡肉


变量指标：

    - 生产数据（如产量、产值、面积、单产等）。
    - 贸易数据（国际贸易进出口量值）



# 数据库列表

## 国内数据库

### 商务部

《中国农产品进出口月度统计报告》（进出口分类：谷物及谷物制品）

### 国家统计局

《中国统计年鉴》
（1）对外经济贸易
11-3按国际贸易标准分类分进出口商品金额
11-4按商品类章分进出口商品金额
（2）农业（我国粮食生产数据）
12-8农作物播种面积
12-9主要农作物种植结构
12-10主要农产品产量
12-11主要农产品单位面积产量
12-16人均主要农产品产量（人均粮食和人均谷物分开）

### 海关总署

待查询（与统计局数据有差异）


###　农业农村部数据库
（1）种植业
（2）农产品进出口数据（数量/金额）

## 国际数据库

## UNCOMTRADE数据库

（SITC或HS，暂截止2018年数据）


### FAOSTAT数据库

http://www.fao.org/faostat/en/#home
有关粮食，农业，渔业，林业，自然资源管理和营养的世界上最全面的统计数据库。

### 农产品市场信息系统（AMIS）

https://app.amis-outlook.org/#/market-database/supply-and-demand-overview
农业市场信息系统（AMIS）数据库提供了有关四种谷物的市场信息，这四种谷物在国际食品市场中尤其重要：小麦，玉米，大米和大豆。

### 食品价格监测与分析（FPMA）

https://fpma.apps.fao.org/giews/food-prices/tool/public/#/home
食品价格监测和分析工具包含主要在发展中国家的基本食品国内价格的最新信息和分析，补充了粮农组织对国际市场的分析。 它提供了有关国家一级高粮价的预警，可能对粮食安全产生负面影响。

### 美国农业部官网

https://d.qianzhan.com/xdata/list/xCxpxwOxV.html 前瞻数据库
USDA出口销售报告(周)
USDA出口检验报告(周) 
USDA作物生长报告(周) 
USDA大豆压榨报告(周) 
USDA供需报告:市场年度(月) 
USDA供需报告:估计年度(月) 
USDA供需报告:预测年度(月) 
USDA供需报告:市场年度:分地区(月) 
USDA供需报告:估计年度:分地区(月) 
USDA供需报告:预测年度:分地区(月) 
美国全国油籽加工商协会(NOPA)压榨报告(月) 
USDA谷物库存报告(季) USDA种植面积报告(季) 
美国玉米消费量(季) 美国作物生产统计(年) 
USDA供需报告(年) USDA供需报告:分地区(年) 
USDA世界作物产量报告:市场年度(月) 
USDA世界作物产量报告:估计年度(月) 
USDA世界作物产量报告:预测年度(月) 
USDA世界作物产量报告:市场年度:分地区(月) 
USDA世界作物产量报告:估计年度:分地区(月) 
USDA世界作物产量报告:预测年度:分地区(月) 
USDA世界作物产销预测:预测年度:分地区(月) 
USDA牛存栏数报告(半年) USDA世界作物产量:分地区(年)
（1）GATS（Global Agricultural Trade System）
https://apps.fas.usda.gov/gats/default.aspx
有关美国农产品，鱼类，森林和纺织产品国际贸易的当前和历史数据。
（2）PS&D（Production, Supply and Distribution）
https://apps.fas.usda.gov/psdonline/app/index.html#/app/home
有关美国以及主要生产国和消费国的农产品生产，供应和分配的数据。
