---
title: "Git技术篇2: 追踪(Track)、叉取(Fork)github仓库"
author: "hawkingwu"
date: "2020/11/26"
output: 
  bookdown::word_document2: 
    fig_caption:  true
    reference_docx: ../template/create-template.docx
    toc: no
    number_sections: no
  bookdown::html_document2:
    number_sections: no
    toc: yes
    fig_caption:  true
    toc_float: true
  bookdown::pdf_document2:
    latex_engine: xelatex
    fig_caption:  true
    includes:
      in_header: ../latex/header.tex
      before_body: ../latex/preamble.tex
    toc: yes
    toc_depth: 5
    number_sections: no
    keep_tex: true
bibliography: 
  - ../bib/sco.bib
biblio-style: "bib/nnsfc.csl"
csl: "../bib/nnsfc.csl"
link-citations: true
always_allow_html: yes
documentclass: article
classoption: [(landscape,a4paper),(portrait,a4paper)]
fontsize: "12pt"
pagestyle: "headings"
knit: (function(inputFile, encoding) { 
      out_dir <- '../public';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'demo-04-track-fork-upstream.docx')) })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. 问题描述

如何将GitHub中的fork项目保持与原作者的仓库同步更新。

# 2. 具体情景

- 确保Fork的本地项目文件夹是从自己的云端仓库 git clone

- 输入`cd /DISK_NAME/FILE_NAME/PRO_NAME`进入本地项目文件夹；例` cd /d/project/team-students`

- 输入`git remote -v`查看本地项目文件夹来源；前两列`orgin`部分出现**YOUR_NAME**则为正确，否则需重新克隆

# 3. 两种思路

## 3.1 先本地，后云端（git bash操作）

a. 具体思路：使用**`upstream URL`**将源项目文件更新到本地文件夹中，再使用**`git push`**将更新的本地文件推送到云端仓库，这样就实现了本地和云端的更新

b. 具体操作：

    - **确保step2操作已完成**
    
    - `git remote add upstream URL` 添加更新链接 **注:此URL为源仓库项目地址** 
    
    - `git fetch upstream` 获取更新 
    
    - `git merge upstream/master` 合并更新文件
    
    - `git push` 推送云端

c. 存在问题：在`git merge/git push`过程中，可能会提示错误：

>Please enter a commit message to explain why this merge is necessary, especially if it merges an updated upstream into a topic branch


>解决方法[点击参考](https://www.cnblogs.com/wei325/p/5278922.html)

d. 后续更新步骤：重复 `git fetch、git merge、git push` 即可。

## 3.2 先云端，后本地 （GitHub网站）

- 原理是从GitHub网站上将云端项目更新，然后利用再克隆到本地项目中。

- 推荐链接： https://blog.csdn.net/qq1332479771/article/details/56087333

- **流程复杂，容易出错，不推荐**



