---
title: "rmarkdown下的自动化文献管理和引用"
author: "组会团队"
date: "`r Sys.Date()`"
output: 
  bookdown::word_document2: 
    fig_caption:  true
    reference_docx: ../template/create-template.docx
    toc: yes
    number_sections: no
  bookdown::html_document2:
    number_sections: no
    toc: yes
    fig_caption:  true
    toc_float: true
  bookdown::pdf_document2:
    latex_engine: xelatex
    fig_caption:  true
    includes:
      in_header: ../latex/header.tex
      before_body: ../latex/preamble.tex
    toc: yes
    toc_depth: 5
    number_sections: no
    keep_tex: true
bibliography: 
  - ../bib/sco.bib
biblio-style: "bib/nnsfc.csl"
csl: "../bib/nnsfc.csl"
link-citations: true
always_allow_html: yes
documentclass: article
classoption: [(landscape,a4paper),(portrait,a4paper)]
fontsize: "12pt"
pagestyle: "headings"
knit: (function(inputFile, encoding) { 
      out_dir <- '../public';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'demo-01-rmarkdown-using.docx')) })

---


```{r global_options, echo=F,message=FALSE,warning=F}
source("../R/set-global.R")
```


# 记录

大厦的方法士大夫的沙发

无序清单

- 任务1

- 任务2


有序列表

a. task1

b. task2


```{r, echo= TRUE}
x <- 123
```

