---
title: "rmarkdown下的自动化文献管理和引用"
author: "胡华平"
date: "`r Sys.Date()`"
output: 
  bookdown::word_document2: 
    fig_caption:  true
    reference_docx: create-template.docx
  bookdown::html_document2:
    number_sections: yes
    toc: yes
    fig_caption:  true
    toc_float: true
  bookdown::pdf_document2:
    latex_engine: xelatex
    fig_caption:  true
    includes:
      in_header: header.tex
      before_body: preamble.tex
    toc: yes
    toc_depth: 5
    number_sections: no
    keep_tex: true
  html_document:
    number_sections: yes
    toc: yes
  pdf_document: 
    latex_engine: xelatex
    includes:
      in_header: header.tex
    toc: true
    toc_depth: 3
    number_sections: true
  word_document:
    toc: true
    toc_depth: 3
    fig_caption: yes
bibliography: bib-paper.bib
biblio-style: "apalike"
link-citations: true
always_allow_html: yes
documentclass: article
classoption: [(landscape,a4paper),(portrait,a4paper)]
fontsize: "12pt"
thanks: "感谢经济管理学院数量经济学教研室同仁的大力支持！"
pagestyle: "headings"
---


```{r global_options, echo=F,message=FALSE,warning=F}
source("../R/set-global-only.R")
```


# 记录

大厦的方法士大夫的沙发

无序清单

- 任务1

- 任务2


有序列表

a. task1

b. task2


```{r, echo= TRUE}
x <- 123
```

