---
title: "开题报告"
subtitle: "区域共同体框架下农业创新合作治理与发展评估  \n ——以上合组织农业基地为例"
author: ""
date: "`r Sys.Date()`"
output: 
  bookdown::word_document2: 
    fig_caption:  true
    reference_docx: ../template/create-template.docx
    toc: no
    number_sections: no
  bookdown::html_document2:
    number_sections: no
    toc: yes
    fig_caption:  true
    toc_float: true
  bookdown::pdf_document2:
    latex_engine: xelatex
    fig_caption:  true
    includes:
      in_header: latex/header.tex
      before_body: latex/preamble.tex
    toc: yes
    toc_depth: 5
    number_sections: no
    keep_tex: true
bibliography: ../bib/agri-trade.bib
biblio-style: "../bib/chinese-gb7714-2005-author-date.csl"
csl: "../bib/chinese-gb7714-2005-author-date.csl"
link-citations: no
always_allow_html: yes
documentclass: article
classoption: [(landscape,a4paper),(portrait,a4paper)]
fontsize: "12pt"
thanks: "感谢经济管理学院数量经济学教研室同仁的大力支持！"
pagestyle: "headings"
knit: (function(inputFile, encoding) { 
      out_dir <- '../public';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'research-plan.docx')) })
---

```{r out-source, warning=FALSE, message=FALSE, echo=FALSE}
source("../R/set-global.R", encoding = "UTF-8")
#source("R/xfun-general.R", encoding = "UTF-8")
num_fig <- 0
num_tab <- 0

country_eng <- c("Russian Federation","India","Kazakhstan","Kyrgyzstan",
                 "Tajikistan","Uzbekistan","Pakistan")

country_chn <- c("俄罗斯","印度","哈萨克斯坦","吉尔吉斯斯坦",
                 "塔吉克斯坦","乌兹别克斯坦","巴基斯坦")
```

\newpage

```{=html}
<!---

上合国家成员情况（外交部[官方介绍](https://www.fmprc.gov.cn/web/gjhdq_676201/gjhdqzz_681964/lhg_683094/jbqk_683096/t528036.shtml)）：

**成员国**8个：中国、俄罗斯(Russia)、哈萨克斯坦(Kazakhstan)、吉尔吉斯斯坦(Kyrgyzstan)、塔吉克斯坦(Tajikistan)、乌兹别克斯坦(Uzbekistan)、印度(India)和巴基斯坦(Pakistan)。

**观察员国**4个：阿富汗、白俄罗斯、伊朗、蒙古

**对话伙伴国**6个：阿塞拜疆、亚美尼亚、柬埔寨、尼泊尔、土耳其、斯里兰卡

--->
```

# 0 选题参考

- 农产品贸易转移。

- 自由贸易协定(FTA)下国家贸易流的非对称性问题。简评：自由贸易。

- 国家政策文本分析。特点：数据可获得；方法新颖。建议从英文数据库。

- GTAP建模分析。属于一般均衡模型。

- 公司境外投资情况。

- 国际农业科技培训。

# 1 数据库

## 世贸组织自由贸易协定

区域贸易协议数据库 [Regional Trade Agreements Database](http://rtais.wto.org/UI/PublicMaintainRTAHome.aspx)。可以查到各个国家的贸易协议签订情况。

变量定义文档[pdf](http://rtais.wto.org/UserGuide/User%20Guide_Eng.pdf)

协议类型(Type):

1. CU: Customs Union
2. FTA: Free Trade Agreement
3. PSA: Partial Scope Agreement
4. EIA：Economic Integration Agreement
5.　Free Trade Agreement & Economic Integration Agreement
6. Partial Scope & Economic Integration Agreement
7. Customs Union & Economic Integration Agreement



# 一、选题的范围

本研究的选题拟定为：**区域共同体框架下农业创新合作治理与发展评估**——以上合组织农业基地建设为例。

本研究的主要议题将涉及如何提升区域共同体框架下农业创新合作的公共治理水平和社会服务能力。本研究考察的区域共同体框架主要是指上海合作组织（Shanghai Cooperation Organization, SCO），并具体聚焦于该国际组织框架下新近成立和逐步发展的一种创新区域农业合作模式——**上海合作组织农业技术交流培训示范基地**（简称“上合组织农业基地”）。

2019年6月14日，国家主席习近平在上海合作组织成员国元首理事会第十九次会议上提出，“中方愿在陕西省设立上海合作组织农业技术交流培训示范基地，加强同地区国家现代农业领域合作”。2020年10月，上海合作组织成员国第五次农业部长会议上，各成员国形成共识通过了基地建设倡议，一致同意在陕西杨凌建立上海合作组织农业技术交流培训示范基地（下面简称“上合组织农业基地”）。上合组织农业基地在提出和初始发展阶段坚持“以我为主、稳步推进、重点突破、务求实效”的合作方针，提出“中央领导、省部共建、基地运作”的发展模式，并规划设计“一基地多平台、一中心多园区、一院多所”的实施方案，重点开展在“农业技术交流合作”、“农业技术教育培训”、“农业技术示范推广”、“农业贸易和产能合作”等领域的国际创新农业合作与交流。


# 二、选题意义


## 1.理论意义

本研究拟构建针对区域共同体框架下农业创新合作治理的理论架构和分析方法，这将是对已有前沿研究基础的一种有益理论补充和可能创新。同时，本研究还将构建一套农业创新合作服务能力和水平评估体系，用来帮助持续开展对相关大型国际合作组织或国际合作项目的评估分析和服务改善，这套评估体系也将具有一定的理论扩展性。

## 2.现实意义

区域经济一体化是现代国际关系中的一个重要特征和趋势，它影响着世界经济的发展方向。经过近20年的发展，上合组织已经成为当今世界最具影响力的国际组织之一。在上合组织这一区域共同体框架下，逐步建立和完善相关治理和协调机制。上合组织成员国在政治、经贸、科技、文化、教育、能源、交通、旅游、环保及其它领域的合作取得了卓有成效的合作成就。中国与上合组织成员国的双边贸易额从2001年成立初期的122亿美元起步，到2019年已稳步增长至2588亿美元。虽然上合组织国家间农业贸易和农业投资总额有所增长，但占经济贸易总而比重偏低。中国对上合组织国家的投资也主要集中在能源、矿产资源开发、电力、轻工等领域，对农业领域的投资所占比重较小。

此外，上合组织成员国在农业领域的国际合作还缺乏组织协调上发力点和推动器。目前上合政府合作机制框架下，与农业领域支持最直接相关的主要是上合组织成员国总理会议、农业部长会议、经贸部长会议、财政部长和央行行长会议，以及1个经贸高官会和6个专业工作组（分别是贸易便利化工作组、投资促进工作组、电子商务工作组、过境潜力工作组、海关合作工作组和信息通信工作组）等议事机制予以保障。显然，上合组织农业基地的成立和建设，将是在现有区域共同体框架下，为农业领域国际创新合作提供一种全新治理机制和发展模式选择。然而，区域共同体发展进程的必然会受到上合成员国家发展历史、财政和行政制度、自然资源禀赋、粮食供应安全等差异决定。

因此，如何提升区域共同体框架下农业创新合作的公共治理水平和国际服务能力，将必然成为上合组织农业基地长期建设中需要致力于解决的重大现实问题。本研究将全面梳理全球视野下区域一体化农业合作发展模式，总结成功经验和失败教训，探究背后的治理机制原理，提出可行性发展路径和方案，为上合组织农业基地的中长期建设和可持续合作发展提供决策依据。


## 3.对本单位和本人的意义

上合组织农业基地的提出和建设，实现了从我国单边倡议到上合组织成员国集体行动的转变，开创了上合组织框架下国际农业创新合作交流的历史先河。上合组织农业基地将逐步建成一批现代农业研究中心、国际联合实验室、农业技术推广应用平台，并深入开展上合组织国家农业科研交流合作、现代农业科技人才培养培训、国际农业产业园区建设，实现上合组织区域间互利共赢。

上合农业基地建设的顺利推进实施和探索研究，将有利于形成上合组织国家和地区一体化发展的现代农业体系，开创农业领域交流、培训、示范新模式、新机制；有利于充分发挥我国农业科技优势和国际引领作用，占领技术与合作的制高点；同时加快推进上合农业基地建设，也将进一步为经济社会拓展新平台、注入新活力、汇集新动能，有利于推动陕西和杨凌示范区实现高质量发展，提升国际知名度和影响力。

从个人的角度来看，本课题的研究过程，将有助于把课堂上所学的理论知识融会贯通并应用于实际当中去，有助于锻炼自己分析问题和解决问题的能力，有助于得到科学严谨的工作作风的训练，它将是个人未来的职业生涯发展的一个重要里程碑。


# 三、本研究的目的

本研究将全面梳理全球视野下区域一体化农业合作发展模式，总结成功经验和失败教训，探究背后的治理机制原理，重点深入分析上合组织农业基地的合作治理模式和发展路径选择，为全面提升上合组织农业基地的公共治理水平和国际服务能力提出解决方案和相关政策建议。


# 四、预期成果（可能的研究结论）

（1）本研究将提出一个专门针对区域共同体框架下农业创新合作治理的理论分析方法，其中会整合利用自由贸易区理论和共同市场理论、公共经济学理论、技术扩散理论等。

（2）本研究将全面梳理总结全球视野下区域一体化农业合作发展模式，总结成功经验和失败教训，并进一步提出上合农业基地有效运行的发展模式和现实路径选择。

（3）本研究还将构建一套农业创新合作服务能力和水平评估体系，全面析长期动态博弈下、多主体目标和激励兼容等复杂问题，用来帮助持续开展评估分析和服务改善。

# 五、研究方案（论文初步大纲）

**区域共同体框架下农业创新合作治理与发展评估**——以上合组织农业基地建设为例。

1.区域共同体框架下农业合作发展现状

- 1.1 上合组织农业基地发展情况

- 1.2 区域一体化与农业合作的国际经验

- 1.3 相关理论及评述

2.农业创新合作模式及治理机制

- 2.1 典型合作模式及比较

- 2.2 治理机制及原理分析

- 2.3 上合组织农业基地的治理体系

3.农业创新合作发展路径与选择

- 3.1 动态发展与长期规划

- 3.2 路径设计与现实选择

- 3.3 上合组织农业基地的发展路线图

4.农业创新合作服务水平及评估

- 4.1 评估原理和方法

- 4.2 评估体系的构建

- 4.3 对上合组织农业基地的服务评估运用

5.发展政策及决策建议


# 六、研究方法及其论证

<!---
1.在复杂变化的国际形势下，开展区域共同体框架下农业创新合作治理的尝试和努力，必然面临诸多条件制约和发展挑战。尤其是新冠病毒疫情后，全球经济发展低迷不振，国际政治关系更加复杂和不确定性，整合协调区域资源以实现农业协同发展的阻力进一步增大。--->


（1）首先提出问题，并对问题进行阐述；

（2）运用框架，提出分析问题的主要逻辑框架；

（3）根据逻辑框架，进行详细研究分析；

（4）对各项分析进行汇总，得出结论；

（5）根据结论和有关理论，提出解决问题的方法和建议。

# 七、关键难点及拟采取的解决措施

**1.关键难点**：

**（1）如何在既有的区域共同体框架下运行一种创新的农业合作治理模式，需要寻找更科学和严谨的理论体系加以支撑，这是本研究中的关键难点之一。**根据自由贸易区理论和共同市场理论，越是在复杂多边的国际关系中，区域经济合作能有效抵制或化解金融危机造成的经济衰退后果，因此区域和双边自由贸易协定（FTA）成为开展农业合作与农业科技竞争的重要手段。根据公共经济学理论，上合农业基地的区域性农业合作关系与服务可以被视作一种全球公共社会产品，因此必须考虑到合作关系和合作服务的分割性、排他性和竞争性特征。根据技术扩散理论，农业科技与技术服务天然会存在技术扩散的“溢出效应”，上合农业基地的创新发展也不能脱离农业生产模式和现代农业技术在区域或组织内产生、采纳、扩散、竞争、退出的技术周期规律。总之，目前还缺乏关于对上海合作组织框架下进一步运行上合农业基地这类创新合作治理模式的有效理论解释和理论指导。

**（2）如何在实践中探索区域共同体框架下切实有效运行的农业合作运行模式和实施方案，是本研究中的下一个关键难点。**以技术创新为源泉的“硅谷”模式或者以金融市场见长的“华尔街”模式，显然并不适用于区域化、多边型的农业协同创新发展，上合农业基地长期发展需要做出符合实际的现实发展路径选择。最为重要是需要确立短期和中长期合作发展的基本原则。在区域农业合作起步阶和后续深化区域农业合作阶段段，对农业投资与农业贸易、货物贸易与服务贸易、资源领域合作与非资源领域合作等做出轻重缓急和先后次序等发展关系上的合理安排，并对发展思路达成各方一致认可。除此之外，还要系统考虑上合组织各成员国不对称的政治、经济和社会等真实实力关系，统筹安排上合农业基地的战略规划、运行经费、科技支撑、人员组织、项目管理等方方面面。总之，上合农业基地的现实合作运行路径和实际实施开展，总会离不开系统考虑、复杂设计、持久谈判和长期不懈的推进努力。

**（3）如何系统构建农业创新合作服务能力和水平评估体系，这是本研究中的第3个关键难点。**上海合作组织已经拥有近20年的发展历史，参与国家也不断得到扩充，参与国家的身份类型呈现多样化（包括成员国、伙伴国和观察国）。农业贸易和农业投资虽然在整个区域经济合作中的比例和强度都不是特别高，但所有上合成员国都将农业部门视作国际合作中最重要经济部门，也总是国际合作谈判中最难达成一致实际行动的议题领域。因此农业创新合作服务能力和水平评估体系的建立，必然需要考虑到不同的成员国农业条件及服务能力的供给和需求水平差异，尤其是需要整合分析长期动态博弈下、多主体目标和激励兼容等复杂问题。总之，农业创新合作服务能力和水平评估体系的设计既要求科学客观反映多方实际需要，又要兼顾区域共同体整体长远目标，因而还特别需要系统化、动态化掌握上合成员国基本国情及国际互动关系变化，并进行全面的数据收集和定量统计分析。


**2.解决措施**：

（1）系统阅读研究文献（不少于35篇参考文献），查阅相关方面的最新研究进展。

（2）及时请教指导教师，保持密切有效沟通，持续改进研究思路和内容体系。

（3）深入调查研究，取得全面准确的数据，充分利用本人的工作专长经验，随时对工作所在单位开展各类访谈和调研工作。


# 八、论文工作总体日程安排


# 九、预计答辩时间




